coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 5%
        informational: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: unit
      paths:
        - src/
      carryforward: true

comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: true

ignore:
  - 'src/**/*.d.ts'
  - 'src/db/**'
  - 'src/app/**/*.tsx'
  - 'src/middleware.ts'
  - 'tests/**'
  - '**/*.test.ts'
